### PR TITLE
Fix non working xref in preview pane

### LINKED ISSUE #425: Does asciidoc have issues with xref and include?
## Description

Given:
```
:revnumber: v0.1
:revdate: 16.09.2020
:revremark: First draft
:imagesdir: ./img
:toc: top
:icons: font
:experimental: true
:relfilesuffix: .adoc
:relfileprefix: ./chapters/

== Links

image::logo_docker.png[Docker]
xref:docker.adoc[docker]

xref:aws.adoc[aws]

image::logos/logo_azure.png[Azure]
xref:azure.adoc[azure]

xref:infra/ports.adoc[ports]

== Training

include::jobs.adoc[]

include::training/javascript/style.adoc[]

link:https://javascript.info[the javascript training page]
```

When using the preview pane of vscode:

- Both images are fine.
- The xref do not work. Instead, when the xref is clicked on the browser will open with the error: _Check if there is a typo in file+.vscode-resource.vscode-webview.net._
- The include without pathing works.
- The include with pathing does not work. Instead, the preview pane shows: _Unresolved directive in <stdin>_ 
- The link works.

## System Information

Using

- windows 10 home edition.
- vscode 1.58.2, user setup
- asciidoc 2.8.9

## Additional Context

I really want to use asciidoc as a local document repo, a styled way to store tons of notes with tables and images in a hierarchal file structure with the potential to export as HTML.

Is my markup incorrect or does asciidoc have issues with xref and include?

### PR DESCRIPTION
**Pull request by ViToni**
Both `xref:` and `link:` create `<a>` elements. For `xref:` the `data-href` attribute was missing so WebView didn't treat it as a regular link. Now `xref:` and `link:` are created the same way for the WebView thus allowing `xref:` navigation.

Resolves #425.

### CODE REVIEW

File: preview-src/index.ts [hunk 1]
```diff
@@ -82,7 +82,7 @@ const onUpdateView = (() => {
 const updateImageSizes = throttle(() => {
   const imageInfo: { id: string, height: number, width: number }[] = []
   const images = document.getElementsByTagName('img')
-  if (images) {
```
Comment (ggrossetie) [inline preview-src/index.ts:85]: is it related to the fix?

File: src/asciidoctorWebViewConverter.ts [hunk 2]
```diff
@@ -202,7 +202,7 @@ export class AsciidoctorWebViewConverter {
       </body>
       </html>`
     }
-    if (nodeName === 'inline_anchor' && node.type === 'link') {
+    if (nodeName === 'inline_anchor' && (node.type === 'link' || node.type === 'xref')) {
```
Comment (ggrossetie) [inline src/asciidoctorWebViewConverter.ts:205]: We should implement this logic: https://github.com/asciidoctor/asciidoctor/blob/2983738317abf6bc125c75eede7890c36a10b86c/lib/asciidoctor/converter/html5.rb#L1131-L1154

File: preview-src/index.ts [hunk 3]
```diff
@@ -82,7 +82,7 @@ const onUpdateView = (() => {
...
+  if (images && images.length > 0) {
```
[the remark this answers is not in the document]
Comment (ViToni) [reply preview-src/index.ts:85]: Indirectly. When looking into the event listener, that clicking on the `xref:` (without any other changes) triggered a `cacheImageSizes` even though there are no images at all in the document I tested with.
It could alos be moved to a dedicated PR.

[the remark this answers is not in the document]
Comment (ggrossetie) [reply preview-src/index.ts:85]: Indeed, good catch

File: src/asciidoctorWebViewConverter.ts (hunk 2 above)
Comment (ViToni) [reply src/asciidoctorWebViewConverter.ts:205]: The Ruby code seems quite complex as it resolves the given `refid`s for non-file `xref:`s. Haven't found code yet which would do something similar. Any hints?

Comment (ggrossetie) [reply src/asciidoctorWebViewConverter.ts:205]: Asciidoctor.js is transpiled from Ruby to JavaScript. So we should have access to all the Asciidoctor methods.

I can help you implement the non-trivial parts.

Comment (ViToni) [reply src/asciidoctorWebViewConverter.ts:205]: Currently I have something like this:

```TypeScript
      if (node.type === 'xref') {
        const attrs = []
        if (node.hasAttribute('role')) { attrs.push(` class="${node.getRole()}"`) }

        let text: string
        if (typeof (node.text) === 'string') {
          text = node.text
        }
        const path = node.getAttribute('path')
        if (typeof path === 'string') {
          if (typeof (text) === 'undefined') {
            text = node.getAttribute('path')
          }
        } else {
          // const refid = node.getAttribute('refid')

          // PSEUDO CODE:
          // const refNode = getNodeId(refid)
          //
          // if (refNode.hasAttribute('xrefstyle')) {
          //   const xrefstyle = refNode.getAttribute('xrefstyle')
          //   text = computeText(refnode, xrefstyle)
          // } else {
          //   text = refnode.getTitle()
          // }
        }
        attrs.push(` href="${node.target}"`)
        attrs.push(` data-href="${node.target}"`)
        return `<a${attrs.join()}>${text}</a>`
      }
```

Regular `xref:` to files works quite fine. What I don't know how to solve is the `xref:` to sections in the `PSEUDO CODE` section.
I don't know if there is something like a `computeText` method. I saw that using e.g. `reftext` on sections doesn't change anything in `:toc:`. Don't know if its not handled on purpose or there might be a gap.

Comment (ggrossetie) [reply src/asciidoctorWebViewConverter.ts:205]: You should be able to get the catalog `node.document.catalog[:refs]`

```js
node.getDocument().getCatalog()['refs']
```

Comment (ggrossetie) [reply src/asciidoctorWebViewConverter.ts:205]: The Opal/Asciidoctor.js syntax for this part `AbstractNode === ref` is probably a bit complex but you can inspect the `ref`, it should contain a class name.

**Comment by ViToni** [comment]
@ggrossetie I'd say it looks good:

grafik

wdyt?

File: src/asciidoctorWebViewConverter.ts (hunk 2 above)
Comment (ViToni) [reply src/asciidoctorWebViewConverter.ts]: @ggrossetie I'd say it looks good:

grafik

wdyt?

Comment (ViToni) [reply src/asciidoctorWebViewConverter.ts]: I'd like to add some tests `src/test/asciidoctorWebViewConverter.test.ts` but am not sure how execute them.

Comment (ViToni) [reply src/asciidoctorWebViewConverter.ts]: One can run tests by
```shell
npm run build && node ./dist/src/test/runTest.js
```

Comment (ViToni) [reply src/asciidoctorWebViewConverter.ts]: @ggrossetie If you could spare some time, could you take a look at the tests?
I added test to `src/test/asciidoctorWebViewConverter.test.ts` but the ones referring to files are failing because expected / actual are not matching.
In the actual output all `.adoc` suffixes are replaced by `.html` which is really not expected.

Comment (ggrossetie) [reply src/asciidoctorWebViewConverter.ts]: Thanks for taking the time to fix this issue. I will try to find some time tomorrow to push this fix to the finish line.

Comment (ggrossetie) [reply src/asciidoctorWebViewConverter.ts]: Since we are generating an HTML page, Asciidoctor will use `outfilesuffix` / `relfilesuffix`: 

> Since the default suffix for inter-document cross references in the html5 backend is .html, the resulting link created in these environments may end up pointing to non-existent HTML files. In this case, you need to change the inter-document cross references to refer to other AsciiDoc source files instead.

https://docs.asciidoctor.org/asciidoc/latest/macros/inter-document-xref/#navigating-between-source-files

Comment (ViToni) [reply src/asciidoctorWebViewConverter.ts]: So should I change the test or the backend. As the change is for the preview, I'd assume the backend?

Comment (ggrossetie) [reply src/asciidoctorWebViewConverter.ts]: The preview should use the `.adoc` suffix since we will navigate between AsciiDoc files.

I don't recall if we are already doing it but we should set `:relfilesuffix: .adoc` in the preview.

You can update the convert function in the test to use `:relfilesuffix: .adoc` as well. Your assertions should be valid.

Comment (ViToni) [reply src/asciidoctorWebViewConverter.ts]: > I don't recall if we are already doing it but we should set :relfilesuffix: .adoc in the preview.

This could be the place where `:relfilesuffix: .adoc` is set for the preview:
https://github.com/asciidoctor/asciidoctor-vscode/blob/acbb89000276bc1541b2c66385009f59645b3d60/src/features/asciidoctorAttributesConfig.ts#L18-L23

Comment (ggrossetie) [reply src/asciidoctorWebViewConverter.ts]: Yes that's the one 👍🏻

**Comment by ggrossetie** [comment]
All good, thanks 👍🏻
