### PR TITLE
resolves #736 getLineNumber can sometimes return 0 :|

### LINKED ISSUE #736: Error: Illegal argument: line must be non-negative from tableOfContentsprovider
Noticed this stacktrace in console:

```
[Extension Host] Unable to build the Table Of Content for: /home/apupier/ws/asciidoc/my.adoc Error: Illegal argument: line must be non-negative
	at m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:1267)
	at new s (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:13490)
	at /home/apupier/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.0.6/dist/src/tableOfContentsProvider.js:60:61
	at Array.map (<anonymous>)
	at TableOfContentsProvider.buildToc (/home/apupier/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.0.6/dist/src/tableOfContentsProvider.js:55:14)
	at TableOfContentsProvider.getToc (/home/apupier/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.0.6/dist/src/tableOfContentsProvider.js:37:33)
	at AsciidocFoldingRangeProvider.getHeaderFoldingRanges (/home/apupier/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.0.6/dist/src/features/foldingProvider.js:149:57)
	at AsciidocFoldingRangeProvider.provideFoldingRanges (/home/apupier/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.0.6/dist/src/features/foldingProvider.js:34:36)
	at we.provideFoldingRanges (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:59868)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:75474
	at oe.s (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:63904)
	at oe.$provideFoldingRanges (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:75460)
	at s.N (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11717)
	at s.M (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11435)
	at s.H (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:10477)
	at s.G (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:9494)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:8282
	at b.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at d.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:32461
	at b.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at d.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
	at MessagePortMain.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:30587)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
	at Object.callbackTrampoline (node:internal/async_hooks:130:17) (at console.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:161026))
```

The mentioned file content is:
```
= test
include::attrs.adoc[]


content

```

and the content of attrs.adoc is:
```:a-attr3: value3```

### PR DESCRIPTION
**Pull request by ggrossetie**
resolves #736

### CODE REVIEW

File: src/tableOfContentsProvider.ts [hunk 1]
```diff
@@ -45,14 +45,20 @@ export class TableOfContentsProvider {
...
-      .map((section) => ({
-        slug: new Slug(section.getId()),
-        text: section.getTitle(),
-        level: section.getLevel(),
-        line: section.getLineNumber() - 1,
-        location: new vscode.Location(textDocument.uri,
-          new vscode.Position(section.getLineNumber() - 1, 1)),
-      }))
+      .map((section) => {
+        let lineNumber = section.getLineNumber() // Asciidoctor is 1-based but can return 0 (probably a bug/limitation)
```
Comment (ggrossetie) [inline src/tableOfContentsProvider.ts:49]:
```suggestion
        // Asciidoctor is 1-based but since it has to look for setext section titles by default, it advances from the document title line to the include file. However, when it tries to back up, it ends up at line 0 of that include file instead of coming back out of it. That's how we get to line 0.
        // One way to fix the problem is to turn off setext section titles.
        // Asciidoctor::Compliance.underline_style_section_titles = false
        // Unless someone sees a way to fix this particular otherwise, it probably won't be resolved until Asciidoctor gets reworked to use the parsing grammar being proposed in the specification.
        let lineNumber = section.getLineNumber()
```
