### PR TITLE
Fix folding of several single line comments for more than 2 lines

### LINKED ISSUE #722: Folding of several single line comments is not working for more than 2 lines
Please provide details about:

* What you're trying to do
* What happened
* What you expected to happen

Please share relevant sample content. Or better yet, provide a link to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

We'll also need your system information (get it under "Help" -> "About" in VS Code). Share the installed extension version (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd> or <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd> on macOS).

Provide steps to reproduce the issue and, if applicable, add screenshots to make it easier to understand.

https://github.com/asciidoctor/asciidoctor-vscode/assets/1105127/c32809f6-715a-40fc-a797-96957d706a6f

### PR DESCRIPTION
**Pull request by apupier**
resolves #722 

https://github.com/asciidoctor/asciidoctor-vscode/assets/1105127/ae61a81b-4d3f-47e6-8e5c-591d3a27101a

### CODE REVIEW

File: src/features/foldingProvider.ts [hunk 1]
```diff
@@ -96,16 +96,17 @@ export default class AsciidocFoldingRangeProvider implements vscode.FoldingRange
...
+      }
+      if (lineIndex >= documentLineCount - 1) {
         // comment on last line of the document
         const startIndex = singleLineCommentStartIndexes.pop()
         if (lineIndex > startIndex) {
           foldingRanges.push(new vscode.FoldingRange(
             startIndex,
             lineIndex,
-            FoldingRangeKind.Region)
+            FoldingRangeKind.Comment)
```
Comment (apupier) [inline src/features/foldingProvider.ts:109]: using Comment kind avoids having the last line of the folding range to be displayed

**Comment by ggrossetie** [comment]
Looks good to me, thanks!
