### PR TITLE
Issue #444 - Run Kroki extension within class

### LINKED ISSUE #444: Asciidoc: Use_kroki setting change only effective after restarting VS code
## Description

Changes of the Use_kroki setting are only effective after restarting VS code.
## Environment
AsciiDoc v2.8.9

## To Reproduce

Create an asciidoc with an embedded diagram.
Check  Asciidoc: Use_asciidoctor_js 
Uncheck: Asciidoc: Use_kroki
Restart VS code
Preview the asciidoc (no diagrams should be rendered)
Check: Asciidoc: Use_kroki
Refresh the preview (diagrams should be rendered, but are not rendered)
Restart VS code
Refresh the preview (diagrams are rendered,)

### PR DESCRIPTION
**Pull request by danyill**
Closes #444 
This is a rebase of #445.

I have noticed that there appears to be a problem with the highlightjs adapter while testing the rebase of this.

1. With wkhtmltopdf used for PDF generation
2. With `use_kroki` checked try the document below
3. When I export to PDF I receive the following intriguing error:

```bash
[2021-09-29 21:04:08.966] [exthost] [error] TypeError: superclass mismatch for class CustomHighlightJsAdapter
	at ensureSuperclassMatch (/home/mulhollandd/Documents/asciidoctor-vscode/node_modules/asciidoctor-opal-runtime/src/opal.js:479:28)
	at Object.klass (/home/mulhollandd/Documents/asciidoctor-vscode/node_modules/asciidoctor-opal-runtime/src/opal.js:505:9)
	at Object.register (/home/mulhollandd/Documents/asciidoctor-vscode/dist/src/highlightjs-adapter.js:8:43)
	at new AsciidocParser (/home/mulhollandd/Documents/asciidoctor-vscode/dist/src/asciidocParser.js:30:28)
	at ExportAsPDF.<anonymous> (/home/mulhollandd/Documents/asciidoctor-vscode/dist/src/commands/exportAsPDF.js:83:32)
	at Generator.next (<anonymous>)
	at /home/mulhollandd/Documents/asciidoctor-vscode/dist/src/commands/exportAsPDF.js:8:71
	at new Promise (<anonymous>)
	at /home/mulhollandd/Documents/asciidoctor-vscode/dist/src/commands/exportAsPDF.js:4:12
	at ExportAsPDF.execute (/home/mulhollandd/Documents/asciidoctor-vscode/dist/src/commands/exportAsPDF.js:31:16)
	at _executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:110879)
	at _.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111317)
	at i._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13543)
	at i._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13227)
	at i._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:11889)
	at i._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10567)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8663
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30187
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
	at r._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21051)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:17929
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at v.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13142)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12490
	at Socket.w (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13350)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
	at Pipe.callbackTrampoline (internal/async_hooks.js:131:14) asciidoc.exportAsPDF
```

Perhaps I have introduced error? Perhaps there is some prototype pollution?

## Test Document

```asciidoc
= Test of Kroki

[graphviz]
....
digraph G {
  Hello->World
}
....
```

### CODE REVIEW

File: src/asciidocParser.ts [hunk 1]
```diff
@@ -2,26 +2,21 @@ import * as vscode from 'vscode'
...
     public document = null
+    public processor = null
     private extPath = vscode.extensions.getExtension('asciidoctor.asciidoctor-vscode').extensionPath
     private stylesdir = path.join(this.extPath, 'media')
 
     constructor (private readonly filename: string, private errorCollection: vscode.DiagnosticCollection = null) {
-      this.filename = filename
-      this.errorCollection = errorCollection
+      this.processor = asciidoctor()
+      highlightjsAdapter.register(this.processor)
```
Comment (Mogztter) [inline src/asciidocParser.ts:19]: You cannot register the extension more than once. The reason is that we are doing the following in the `register` function:

```
const HighlightjsSyntaxHighlighter = asciidoctor.SyntaxHighlighter.for('highlight.js')
const customHighlightJsAdapter = Opal.klass(Opal.nil, HighlightjsSyntaxHighlighter, 'CustomHighlightJsAdapter')
```

So the first time, we actually get the built-in "HighlightjsSyntaxHighlighter" from Asciidoctor. But, since we replace the built-in syntax highlighter with our "CustomHighlightJsAdapter", the second time the function `asciidoctor.SyntaxHighlighter.for('highlight.js')` will actually return our "CustomHighlightJsAdapter".

That's the reason why I'm doing the following in #451:

```js
// top definition, called only once
const highlightjsBuiltInSyntaxHighlighter = asciidoctor.SyntaxHighlighter.for('highlight.js')

// ...

// can be called multiple times
highlightjsAdapter.register(highlightjsBuiltInSyntaxHighlighter, context, editor)
```


**src/highlightjs-adapter.ts**

```js
module.exports.register = (highlightjsBuiltInSyntaxHighlighter, context: vscode.ExtensionContext, webviewPanel: vscode.WebviewPanel) => {
  const customHighlightJsAdapter = Opal.klass(Opal.nil, highlightjsBuiltInSyntaxHighlighter, 'CustomHighlightJsAdapter')
  // ...
}
```

**Comment by danyill** [comment]
I've rebased this again and merged and dealt with a small issue in the way the highlighting registration/syntax highlighter was called. The rebase was quite a time-consuming process and I hope not to have introduced an error but it's difficult to be sure as the commit diffs were especially messy.

File: src/asciidocParser.ts (hunk 1 above)
Comment (danyill) [reply src/asciidocParser.ts]: I almost understand :confounded:

File: src/asciidocParser.ts [hunk 2]
```diff
@@ -284,9 +286,9 @@ export class AsciidocParser {
       adocCmdArgs.push('-a', 'env-vscode')
 
       adocCmdArgs.push('-q', '-B', '"' + baseDir + '"', '-o', '-', '-')
-      const asciidoctor = spawn(adocCmd, adocCmdArgs, options)
+      spawn(adocCmd, adocCmdArgs, options)
 
-      asciidoctor.stderr.on('data', (data) => {
+      this.processor.stderr.on('data', (data) => {
```
Comment (Mogztter) [inline src/asciidocParser.ts:291]: @danyill Reading this again, I think the code is incorrect. In this case, the `asciidoctor` variable was referring to the command spawned by the `spawn` function.

`stdout` and `stderr` are not available on the Asciidoctor processor and will most likely throw an exception when using the Asciidoctor CLI instead of Asciidoctor.js.

File: src/asciidocParser.ts [hunk 3]
```diff
@@ -2,26 +2,21 @@ import * as vscode from 'vscode'
...
   public html: string = ''
   public document = null
+  public processor = null
   private extPath = vscode.extensions.getExtension('asciidoctor.asciidoctor-vscode').extensionPath
   private stylesdir = path.join(this.extPath, 'media')
 
   constructor (private readonly filename: string, private errorCollection: vscode.DiagnosticCollection = null) {
-    this.filename = filename
-    this.errorCollection = errorCollection
+    this.processor = asciidoctor()
```
Comment (Mogztter) [inline src/asciidocParser.ts:19]: I don't think we need to instantiate the `processor` in the constructor, do we?
Most of the time we can do:

```js
const processor = require('@asciidoctor/core')()
```

In the future, we might be able to write:

```js
import { convert } from '@asciidoctor/core'
```

The reason we have a constructor in Asciidoctor.js is merely a workaround because Opal will modify basic object prototypes. So in some cases, it's important to decide when Opal is effectively loaded.

```js
// Opal not yet loaded
const Asciidoctor = require('@asciidoctor/core')

// ... do some work

// Load Opal!
const processor = Asciidoctor()
```

File: src/asciidocParser.ts [hunk 4]
```diff
@@ -284,9 +286,9 @@ export class AsciidocParser {
       adocCmdArgs.push('-a', 'env-vscode')
 
       adocCmdArgs.push('-q', '-B', '"' + baseDir + '"', '-o', '-', '-')
-      const asciidoctor = spawn(adocCmd, adocCmdArgs, options)
```
Comment (Mogztter) [inline src/asciidocParser.ts:287]: We should probably rename this variable to `asciidoctorProcess` to make it clear that we are dealing with the Asciidoctor CLI process.

File: src/asciidocParser.ts (hunk 3 above)
Comment (danyill) [reply src/asciidocParser.ts:19]: I have a habit of "objectifying" everything.... I will fix.

**Comment by danyill** [comment]
Thanks for catching this :pray:. I've only recently learnt the "Replace Symbol" command and this was a little careless, I think I've fixed in #461.
